---
name: Touch Main Screen Windows CI
permissions: {}

on:
  push:
    branches:
      - touch-send-to-mainscreen-only-poc
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build-windows:
    name: Windows
    permissions:
      contents: read
    uses: ./.github/workflows/ci-windows.yml
    with:
      publish_release: 'false'
      release_commit: ${{ github.sha }}
      release_version: '0.0.0'
